- project:
    check:
      jobs:
        - thoth-coala
        - thoth-pytest
    gate:
      queue: thoth-station/amun-api
      jobs:
        - thoth-coala
        - thoth-pytest
    release:
      jobs:
        - upload-pypi-sesheta
    kebechet-auto-gate:
      queue: thoth-station/amun-api
      jobs:
        - thoth-coala
        - thoth-pytest
